# Generated by Django 6.0.2 on 2026-03-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المنشأة')),
                ('city', models.CharField(default='Riyadh', max_length=80, verbose_name='المدينة')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64, verbose_name='المنطقة الزمنية')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منشأة',
                'verbose_name_plural': 'المنشآت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='core_farm_name_30a09f_idx'), models.Index(fields=['is_active'], name='core_farm_is_acti_0cacd4_idx')],
            },
        ),
    ]
