# Generated by Django 6.0.2 on 2026-03-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='city',
            field=models.CharField(default='الرياض', max_length=80, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف'),
        ),
    ]
