# Generated by Django 6.0.2 on 2026-03-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المجموعة')),
                ('species', models.CharField(choices=[('SHEEP', 'غنم'), ('GOAT', 'ماعز'), ('CAMEL', 'إبل'), ('COW', 'بقر'), ('OTHER', 'أخرى')], default='SHEEP', max_length=20, verbose_name='النوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herd_groups', to='core.farm')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60, verbose_name='الوسم/الترقيم')),
                ('species', models.CharField(choices=[('SHEEP', 'غنم'), ('GOAT', 'ماعز'), ('CAMEL', 'إبل'), ('COW', 'بقر'), ('OTHER', 'أخرى')], default='SHEEP', max_length=20, verbose_name='النوع')),
                ('breed', models.CharField(blank=True, max_length=80, verbose_name='السلالة')),
                ('sex', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('U', 'غير محدد')], default='U', max_length=1, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('status', models.CharField(choices=[('ACTIVE', 'نشط'), ('SOLD', 'مباع'), ('DEAD', 'نافِق'), ('LOST', 'مفقود')], default='ACTIVE', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.farm')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='herd.herdgroup')),
            ],
            options={
                'verbose_name': 'حيوان',
                'verbose_name_plural': 'الحيوانات',
            },
        ),
        migrations.CreateModel(
            name='ReproductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('outcome', models.CharField(choices=[('PREGNANT', 'حمل'), ('BIRTH', 'ولادة'), ('ABORTION', 'إجهاض'), ('UNKNOWN', 'غير محدد')], default='UNKNOWN', max_length=20)),
                ('kids_count', models.PositiveIntegerField(default=0, verbose_name='عدد المواليد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repro_female_records', to='herd.animal')),
                ('male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repro_male_records', to='herd.animal')),
            ],
            options={
                'verbose_name': 'سجل تكاثر',
                'verbose_name_plural': 'سجلات التكاثر',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='الوزن (كجم)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='herd.animal')),
            ],
            options={
                'verbose_name': 'قياس وزن',
                'verbose_name_plural': 'قياسات الوزن',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINE', 'تلقيح'), ('TREATMENT', 'علاج'), ('CHECKUP', 'فحص'), ('OTHER', 'أخرى')], default='CHECKUP', max_length=20)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='herd.animal')),
            ],
            options={
                'verbose_name': 'سجل صحي',
                'verbose_name_plural': 'السجلات الصحية',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['animal', 'date'], name='herd_health_animal__cbf965_idx'), models.Index(fields=['record_type', 'date'], name='herd_health_record__31dafe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='herdgroup',
            index=models.Index(fields=['farm', 'species'], name='herd_herdgr_farm_id_74c255_idx'),
        ),
        migrations.AddConstraint(
            model_name='herdgroup',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uniq_group_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'status'], name='herd_animal_farm_id_246c64_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['farm', 'species'], name='herd_animal_farm_id_a1dbd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(fields=('farm', 'tag'), name='uniq_tag_per_farm'),
        ),
        migrations.AddIndex(
            model_name='reproductionrecord',
            index=models.Index(fields=['female', 'date'], name='herd_reprod_female__14026f_idx'),
        ),
        migrations.AddIndex(
            model_name='reproductionrecord',
            index=models.Index(fields=['outcome', 'date'], name='herd_reprod_outcome_508c31_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['animal', 'date'], name='herd_weight_animal__2c8cd7_idx'),
        ),
    ]
