# Generated by Django 6.0.2 on 2026-03-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_farm_city_alter_farm_phone'),
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='herd.herdgroup', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='herd.animal', verbose_name='الحيوان'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('VACCINE', 'تلقيح'), ('TREATMENT', 'علاج'), ('CHECKUP', 'فحص'), ('OTHER', 'أخرى')], default='CHECKUP', max_length=20, verbose_name='نوع السجل'),
        ),
        migrations.AlterField(
            model_name='herdgroup',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herd_groups', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='reproductionrecord',
            name='female',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repro_female_records', to='herd.animal', verbose_name='الأنثى'),
        ),
        migrations.AlterField(
            model_name='reproductionrecord',
            name='male',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repro_male_records', to='herd.animal', verbose_name='الذكر'),
        ),
        migrations.AlterField(
            model_name='reproductionrecord',
            name='outcome',
            field=models.CharField(choices=[('PREGNANT', 'حمل'), ('BIRTH', 'ولادة'), ('ABORTION', 'إجهاض'), ('UNKNOWN', 'غير محدد')], default='UNKNOWN', max_length=20, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='herd.animal', verbose_name='الحيوان'),
        ),
    ]
