# Generated by Django 6.0.2 on 2026-03-01 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('ADMIN', 'مدير'), ('STAFF', 'موظف'), ('VIEWER', 'مشاهد')], default='STAFF', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عضوية منشأة',
                'verbose_name_plural': 'عضويات المنشآت',
                'indexes': [models.Index(fields=['farm', 'role', 'is_active'], name='accounts_fa_farm_id_851b22_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'farm'), name='uniq_user_farm_membership')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال')),
                ('role', models.CharField(choices=[('OWNER', 'مالك'), ('ADMIN', 'مدير'), ('STAFF', 'موظف'), ('VIEWER', 'مشاهد')], default='STAFF', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.farm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'indexes': [models.Index(fields=['farm', 'role'], name='accounts_pr_farm_id_1274d8_idx'), models.Index(fields=['is_active'], name='accounts_pr_is_acti_d3fcf1_idx')],
            },
        ),
    ]
