# Generated by Django 6.0.2 on 2026-03-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_alter_farm_city_alter_farm_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmembership',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='farmmembership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='farmmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AlterField(
            model_name='farmmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالك'), ('ADMIN', 'مدير'), ('STAFF', 'موظف'), ('VIEWER', 'مشاهد')], default='STAFF', max_length=20, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='farmmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
