# Generated by Django 6.0.2 on 2026-03-01 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('herd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('party_type', models.CharField(choices=[('BUYER', 'مشتري'), ('SELLER', 'بائع'), ('SUPPLIER', 'مورد'), ('OTHER', 'أخرى')], default='OTHER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='core.farm')),
            ],
            options={
                'verbose_name': 'طرف تعامل',
                'verbose_name_plural': 'أطراف التعامل',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('SALE', 'بيع'), ('PURCHASE', 'شراء'), ('EXPENSE', 'مصروف'), ('INCOME', 'دخل'), ('ADJUSTMENT', 'تسوية')], default='EXPENSE', max_length=20, verbose_name='النوع')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('POSTED', 'مرحل'), ('CANCELED', 'ملغي')], default='DRAFT', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='مرجع/فاتورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.counterparty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.farm')),
            ],
            options={
                'verbose_name': 'معاملة',
                'verbose_name_plural': 'المعاملات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('ANIMAL', 'حيوان'), ('SERVICE', 'خدمة'), ('ITEM', 'صنف'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='نوع البند')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الوحدة')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='herd.animal')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='herd.herdgroup')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'بند معاملة',
                'verbose_name_plural': 'بنود المعاملات',
            },
        ),
        migrations.AddIndex(
            model_name='counterparty',
            index=models.Index(fields=['farm', 'party_type'], name='transaction_farm_id_962b94_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(fields=('farm', 'name', 'party_type'), name='uniq_counterparty_per_farm'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['farm', 'date'], name='transaction_farm_id_4937e3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['farm', 'tx_type', 'status'], name='transaction_farm_id_d2af3f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['transaction'], name='transaction_transac_8477a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['animal'], name='transaction_animal__ff8627_idx'),
        ),
    ]
