# Generated by Django 6.0.2 on 2026-03-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_farm_city_alter_farm_phone'),
        ('herd', '0002_alter_animal_farm_alter_animal_group_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='party_type',
            field=models.CharField(choices=[('BUYER', 'مشتري'), ('SELLER', 'بائع'), ('SUPPLIER', 'مورد'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='نوع الطرف'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.counterparty', verbose_name='طرف التعامل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=80, verbose_name='رقم مرجعي/فاتورة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='herd.animal', verbose_name='الحيوان'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='herd.herdgroup', verbose_name='المجموعة'),
        ),
        migrations.AlterField(
            model_name='transactionline',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transactions.transaction', verbose_name='المعاملة'),
        ),
    ]
