# Generated by Django 6.0.2 on 2026-03-01 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_farm_city_alter_farm_phone"),
        ("herd", "0002_alter_animal_farm_alter_animal_group_and_more"),
        (
            "transactions",
            "0002_alter_counterparty_farm_alter_counterparty_notes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transactionline",
            name="transaction_animal__ff8627_idx",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_due",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="المتبقي (آجل)"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="المبلغ المدفوع",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="اسم العميل"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="رقم الجوال"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_mode",
            field=models.CharField(
                choices=[("PAID", "مدفوع"), ("CREDIT", "بالآجل")],
                default="PAID",
                max_length=10,
                verbose_name="طريقة الدفع",
            ),
        ),
        migrations.AddField(
            model_name="transactionline",
            name="livestock_class",
            field=models.CharField(
                choices=[("NONE", "—"), ("JADH", "جذع"), ("THANI", "ثني")],
                default="NONE",
                max_length=10,
                verbose_name="الصنف",
            ),
        ),
        migrations.AddField(
            model_name="transactionline",
            name="livestock_kind",
            field=models.CharField(
                choices=[
                    ("SHEEP", "غنم"),
                    ("GOAT", "ماعز"),
                    ("HARRI", "طليان (حري)"),
                    ("SAWAKNI", "طليان (سواكني)"),
                    ("NAIMI", "طليان (نعيمي)"),
                    ("CAMEL", "إبل"),
                    ("COW", "بقر"),
                ],
                default="SHEEP",
                max_length=20,
                verbose_name="نوع المواشي",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="مرجع/فاتورة"
            ),
        ),
        migrations.AlterField(
            model_name="transactionline",
            name="line_type",
            field=models.CharField(
                choices=[
                    ("ANIMAL", "حيوان"),
                    ("SERVICE", "خدمة"),
                    ("ITEM", "صنف"),
                    ("OTHER", "أخرى"),
                ],
                default="ANIMAL",
                max_length=20,
                verbose_name="نوع البند",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["payment_mode"], name="transaction_payment_1baa30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionline",
            index=models.Index(
                fields=["livestock_kind", "livestock_class"],
                name="transaction_livesto_0deccc_idx",
            ),
        ),
    ]
