# Generated by Django 6.0.2 on 2026-03-02 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_farm_city_alter_farm_phone"),
        (
            "transactions",
            "0003_remove_transactionline_transaction_animal__ff8627_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="المبلغ"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "نقدي"),
                            ("TRANSFER", "تحويل"),
                            ("OTHER", "أخرى"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="طريقة السداد",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ملاحظات"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "سداد",
                "verbose_name_plural": "السداد",
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="مفتاح منع التكرار",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_return",
            field=models.BooleanField(default=False, verbose_name="مرتجع"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_tx",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_txs",
                to="transactions.transaction",
                verbose_name="مرتجع عن",
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(
                fields=["farm", "phone"], name="transaction_farm_id_de361e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["is_return"], name="transaction_is_retu_dcee54_idx"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="transactions.counterparty",
                verbose_name="طرف التعامل",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أُنشئ بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.farm",
                verbose_name="المنشأة",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="transactions.transaction",
                verbose_name="المعاملة",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["farm", "date"], name="transaction_farm_id_b68ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction"], name="transaction_transac_02bb98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["counterparty"], name="transaction_counter_bd8ee3_idx"
            ),
        ),
    ]
