# Generated by Django 6.0.2 on 2026-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_payment_transaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='يستخدم لمنع البيع الآجل إذا تجاوزت مستحقات العميل هذا الحد.', max_digits=12, null=True, verbose_name='حد الائتمان (ريال)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, help_text='يستخدم لحساب المتأخرات وأعمار الديون (Aging). إذا تركته فارغًا سيتم ضبطه تلقائيًا عند وجود متبقي.', null=True, verbose_name='تاريخ الاستحقاق'),
        ),
    ]
