# Generated by Django 6.0.2 on 2026-03-03 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_farm_city_alter_farm_phone"),
        ("transactions", "0005_counterparty_credit_limit_transaction_due_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="مفتاح منع التكرار"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["farm", "tx_type", "status", "is_return"],
                name="transaction_farm_id_395dba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["farm", "counterparty"], name="transaction_farm_id_161472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["farm", "due_date"], name="transaction_farm_id_c7f7ef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("farm", "idempotency_key"),
                name="uniq_idem_per_farm",
            ),
        ),
    ]
