# Generated by Django 6.0.2 on 2026-03-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_alter_transaction_idempotency_key_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="transaction_farm_id_395dba_idx",
        ),
    ]
