# Generated by Django 6.0.2 on 2026-03-01 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('SUMMARY', 'ملخص عام'), ('PROFIT_LOSS', 'أرباح وخسائر'), ('INVENTORY', 'المخزون'), ('HEALTH', 'الصحة'), ('CUSTOM', 'مخصص')], default='SUMMARY', max_length=30, verbose_name='نوع التقرير')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='إعدادات/باراميترات')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='مفضل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='core.farm')),
            ],
            options={
                'verbose_name': 'تقرير محفوظ',
                'verbose_name_plural': 'التقارير المحفوظة',
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات التقرير')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التوليد')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='core.farm')),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='reports.savedreport')),
            ],
            options={
                'verbose_name': 'لقطة تقرير',
                'verbose_name_plural': 'لقطات التقارير',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['farm', 'report_type'], name='reports_sav_farm_id_eb2cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['is_favorite'], name='reports_sav_is_favo_09ec2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedreport',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='uniq_saved_report_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['farm', 'generated_at'], name='reports_rep_farm_id_350aae_idx'),
        ),
    ]
