# Generated by Django 6.0.2 on 2026-03-01 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_farm_city_alter_farm_phone'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsnapshot',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية الفترة'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية الفترة'),
        ),
        migrations.AlterField(
            model_name='reportsnapshot',
            name='saved_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='reports.savedreport', verbose_name='التقرير'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='core.farm', verbose_name='المنشأة'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='إعدادات التقرير'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
